<div class="row">
<div class="span5" style="width:480px;font-size:11px;">
<center><img src="img/fb.png" style="border:0;" alt="/"></center><br />
<strong>Sosiometri</strong> adalah alat yang tepat untuk mengumpulkan data mengenai hubungan-hubungan sosial dan tingkah laku sosial murid (I. Djumhur dan Muh. Surya, 1985 ).
Sosiometri dapat digunakan untuk memperbaiki hubungan sosial antar teman (human relationship) serta menemukan individu mana yang diterima/ditolak dalam kelompok sosial tertentu.<br />
Sedangkan tujuan aplikasi sosiometri adalah untuk:
<ol>
	<li>Memudahkan responden dalam mengisi angket sosiometri (entry data)</li>
	<li>Memudahkan konselor dalam menganalisis hasil pengisian angket sosiometri</li>
	<li>Mempercepat waktu untuk proses pengisian angket sosiometri</li>
	<li>Menyajikan hasil analisis (output) secara cepat dan detail</li>
</ol>
</div>
<div class="span3 img-rounded" style="margin-left:15px;padding:15px;border:1px solid #ccc;">
    <form class="form-horizontal">
		<div class="control-group">
			<label class="control-label" style="width:50px">Nama</label>
			<div class="controls" style="margin-left:65px">
				: <input type="text" class="input-small" placeholder="Nama" style="width:180px;">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" style="width:50px">Kelas</label>
			<div class="controls" style="margin-left:65px">
				: <input type="text" class="input-small" placeholder="Nama" style="width:180px;">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" style="width:50px">Angkatan</label>
			<div class="controls" style="margin-left:65px">
				: <input type="text" class="input-small" placeholder="Nama" style="width:180px;">
			</div>
		</div>
		<div class="control-group">
			<label class="control-label" style="width:50px">Password</label>
			<div class="controls" style="margin-left:65px">
				: <input type="text" class="input-small" placeholder="Nama" style="width:180px;">
			</div>
		</div>
	    <div class="form-actions" style="padding-left:65px">
		    <button type="submit" class="btn btn-primary">Daftar</button>
		    <button type="clear" class="btn">Batal</button>
	    </div>
    </form>
</div>
</div>