<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sosiometri')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>
        <style type="text/css">
        body{
            background: #fff url(img/grid.png);
        }
        </style>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top" style="">
            <div class="navbar-inner">
                <div class="container" style="max-width:800px; padding:10px 15px;">
                    <a class="brand" href="#">Sosiometri</a>
                    <ul class="nav pull-right">
                        <li class="active">
                            <form class="form-inline navbar-search pull-left">
                            <input type="text" class="input-small" placeholder="Username">
                            <input type="password" class="input-small" placeholder="Password">
                            <button type="submit" class="btn btn-primary" style="margin-top:-1px;width:90px;">Login</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container img-rounded" style="max-width:800px;background:#fff; padding:15px;-webkit-box-shadow: 5px 5px 10px 0px rgba(0, 0, 0, 1);box-shadow: 5px 5px 10px 0px rgba(0, 0, 0, 1);">
            <?php echo $this->content; ?>
            <hr>
            <footer class="pull-right">
                <p style="font-size:11px;">&copy; 2010 - <?php echo date('Y') ?> Sandwhich Multimedia</p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>